version: 2

models:
  - name: Company_Data
    config:
      contract:
        enforced: true
    columns:
      - name: employer_name
        data_type: string
        description: "Primary key for each company"
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: count
        data_type: int64
      - name: employer_url
        data_type: string
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: datetime


  - name: LCA_Disclosure
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns:
          - case_number
          - employer_name
    columns:
      - name: case_number
        data_type: string
        tests: [not_null]
      - name: case_status
        data_type: string
      - name: visa_class
        data_type: string
      - name: job_title
        data_type: string
      - name: soc_code
        data_type: string
      - name: soc_title
        data_type: string
      - name: full_time_position
        data_type: string
      - name: begin_date
        data_type: string
      - name: end_date
        data_type: string
      - name: employer_name
        data_type: string
        tests: [not_null]
      - name: trade_name_dba
        data_type: string
      - name: employer_address1
        data_type: string
      - name: employer_address2
        data_type: string
      - name: employer_city
        data_type: string
      - name: employer_state
        data_type: string
      - name: employer_postal_code
        data_type: string
      - name: employer_country
        data_type: string
      - name: employer_province
        data_type: string
      - name: employer_phone
        data_type: string
      - name: employer_phone_ext
        data_type: string
      - name: employer_fein
        data_type: string
      - name: naics_code
        data_type: string
      - name: employer_poc_last_name
        data_type: string
      - name: employer_poc_first_name
        data_type: string
      - name: employer_poc_middle_name
        data_type: string
      - name: employer_poc_job_title
        data_type: string
      - name: employer_poc_address1
        data_type: string
      - name: employer_poc_address2
        data_type: string
      - name: employer_poc_city
        data_type: string
      - name: employer_poc_state
        data_type: string
      - name: employer_poc_postal_code
        data_type: string
      - name: employer_poc_country
        data_type: string
      - name: employer_poc_province
        data_type: string
      - name: employer_poc_phone
        data_type: string
      - name: employer_poc_phone_ext
        data_type: string
      - name: employer_poc_email
        data_type: string
      - name: agent_representing_employer
        data_type: string
      - name: agent_attorney_last_name
        data_type: string
      - name: agent_attorney_first_name
        data_type: string
      - name: agent_attorney_middle_name
        data_type: string
      - name: agent_attorney_address1
        data_type: string
      - name: agent_attorney_address2
        data_type: string
      - name: agent_attorney_city
        data_type: string
      - name: agent_attorney_state
        data_type: string
      - name: agent_attorney_postal_code
        data_type: string
      - name: agent_attorney_country
        data_type: string
      - name: agent_attorney_province
        data_type: string
      - name: agent_attorney_phone
        data_type: string
      - name: agent_attorney_phone_ext
        data_type: string
      - name: agent_attorney_email_address
        data_type: string
      - name: lawfirm_name_business_name
        data_type: string
      - name: state_of_highest_court
        data_type: string
      - name: name_of_highest_state_court
        data_type: string
      - name: secondary_entity
        data_type: string
      - name: secondary_entity_business_name
        data_type: string
      - name: worksite_address1
        data_type: string
      - name: worksite_address2
        data_type: string
      - name: worksite_city
        data_type: string
      - name: worksite_county
        data_type: string
      - name: worksite_state
        data_type: string
      - name: worksite_postal_code
        data_type: string
      - name: wage_unit_of_pay
        data_type: string
      - name: pw_unit_of_pay
        data_type: string
      - name: pw_tracking_number
        data_type: string
      - name: pw_wage_level
        data_type: string
      - name: pw_oes_year
        data_type: string
      - name: pw_other_source
        data_type: string
      - name: pw_other_year
        data_type: string
      - name: pw_survey_publisher
        data_type: string
      - name: pw_survey_name
        data_type: string
      - name: agree_to_lc_statement
        data_type: string
      - name: h_1b_dependent
        data_type: string
      - name: willful_violator
        data_type: string
      - name: support_h1b
        data_type: string
      - name: statutory_basis
        data_type: string
      - name: appendix_a_attached
        data_type: string
      - name: public_disclosure
        data_type: string
      - name: preparer_last_name
        data_type: string
      - name: preparer_first_name
        data_type: string
      - name: preparer_middle_initial
        data_type: string
      - name: preparer_business_name
        data_type: string
      - name: preparer_email
        data_type: string
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: datetime
      - name: received_date
        data_type: datetime
      - name: decision_date
        data_type: datetime
        description: "Relation to Sentiment_Analysis.publication_date"
      - name: original_cert_date
        data_type: datetime
      - name: total_worker_positions
        data_type: int64
      - name: new_employment
        data_type: int64
      - name: continued_employment
        data_type: int64
      - name: change_previous_employment
        data_type: int64
      - name: new_concurrent_employment
        data_type: int64
      - name: change_employer
        data_type: int64
      - name: amended_petition
        data_type: int64
      - name: worksite_workers
        data_type: int64
      - name: total_worksite_locations
        data_type: int64
      - name: wage_rate_of_pay_from
        data_type: float64
      - name: wage_rate_of_pay_to
        data_type: float64
      - name: prevailing_wage
        data_type: float64

    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - case_number
            - employer_name

            




  - name: LCA_Appendix
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns: [case_number, appx_a_date_of_degree]
    columns:
      - name: case_number
        data_type: string
        description: "Part of composite primary key"
        tests:
          - not_null

      - name: appx_a_date_of_degree
        data_type: datetime
        description: "Part of composite primary key"
        tests:
          - not_null

      - name: appx_a_name_of_institution
        data_type: string
      - name: appx_a_no_of_exempt_workers
        data_type: int64
      - name: appx_a_field_of_study
        data_type: string
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: datetime
    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - case_number
            - appx_a_date_of_degree


  - name: LCA_Worksites
    config:
      contract:
        enforced: true
    columns:
      - name: row_id
        data_type: string
        description: "Primary key for each row"
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null

      - name: case_number
        data_type: string
        description: "Foreign key to LCA_Disclosure"
        tests:
          - relationships:
              to: ref('LCA_Disclosure')
              field: case_number

      - name: secondary_entity
        data_type: string
      - name: secondary_entity_business_name
        data_type: string
      - name: worksite_address1
        data_type: string
      - name: worksite_address2
        data_type: string
      - name: worksite_city
        data_type: string
      - name: worksite_county
        data_type: string
      - name: worksite_state
        data_type: string
      - name: worksite_postal_code
        data_type: string
      - name: wage_rate_of_pay_from
        data_type: float64
      - name: wage_rate_of_pay_to
        data_type: float64
      - name: wage_unit_of_pay
        data_type: string
      - name: prevailing_wage
        data_type: float64
      - name: pw_unit_of_pay
        data_type: string
      - name: pw_tracking_number
        data_type: string
      - name: pw_wage_level
        data_type: string
      - name: pw_oes_year
        data_type: string
      - name: pw_other_source
        data_type: string
      - name: pw_survey_publisher
        data_type: string
      - name: pw_survey_name
        data_type: string
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: datetime
      - name: worksite_workers
        data_type: int64
      - name: pw_other_year
        data_type: int64



  - name: Sentiment_Analysis
    config:
      contract:
        enforced: true
    columns:
      - name: publication_date
        data_type: datetime
        description: "Primary key (assuming each summary is tied to a unique timestamp)"
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null

      - name: text_summary
        data_type: string

      - name: sentiment
        data_type: string

      - name: _data_source
        data_type: string

      - name: _load_time
        data_type: datetime



  - name: Single_Registration
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns:
          - employer_name
          - ben_year_of_birth
          - gender
          - agent_first_name
          - agent_last_name
          - mail_addr
    columns:
      - name: employer_name
        data_type: string
        tests: [not_null]
      - name: ben_year_of_birth
        data_type: string
        tests: [not_null]
      - name: gender
        data_type: string
        tests: [not_null]
      - name: agent_first_name
        data_type: string
        tests: [not_null]
      - name: agent_last_name
        data_type: string
        tests: [not_null]
      - name: mail_addr
        data_type: string
        tests: [not_null]
      - name: country_of_birth
        data_type: string
      - name: country_of_nationality
        data_type: string
      - name: fein
        data_type: string
      - name: city
        data_type: string
      - name: state
        data_type: string
      - name: zip
        data_type: string
      - name: lottery_year
        data_type: string
      - name: status_type
        data_type: string
      - name: ben_multi_reg_ind
        data_type: string
      - name: rec_date
        data_type: string
      - name: first_decision
        data_type: string
      - name: first_decision_date
        data_type: string
      - name: i129_employer_name
        data_type: string
      - name: pet_street
        data_type: string
      - name: pet_city
        data_type: string
      - name: pet_state
        data_type: string
      - name: pet_zip
        data_type: string
      - name: requested_class
        data_type: string
      - name: basis_for_classification
        data_type: string
      - name: requested_action
        data_type: string
      - name: number_of_beneficiaries
        data_type: string
      - name: ben_sex
        data_type: string
      - name: ben_country_of_birth
        data_type: string
      - name: ben_current_class
        data_type: string
      - name: job_title
        data_type: string
      - name: worksite_street
        data_type: string
      - name: worksite_city
        data_type: string
      - name: worksite_state
        data_type: string
      - name: worksite_zip
        data_type: string
      - name: full_time_ind
        data_type: string
      - name: wage_amt
        data_type: string
      - name: wage_unit
        data_type: string
      - name: valid_from
        data_type: string
      - name: valid_to
        data_type: string
      - name: num_of_emp_in_us
        data_type: string
      - name: s1q1a
        data_type: string
      - name: s1q1b
        data_type: string
      - name: ben_education_code
        data_type: string
      - name: ed_level_definition
        data_type: string
      - name: ben_pfield_of_study
        data_type: string
      - name: ben_comp_paid
        data_type: string
      - name: dot_code
        data_type: string
      - name: naics_code
        data_type: string
      - name: s3q1
        data_type: string
      - name: s4q1
        data_type: string
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: datetime




  - name: Wage_Summary
    config:
      contract:
        enforced: true
    constraints:
      - type: primary_key
        columns:
          - company_name
          - job_title
    columns:
      - name: company_name
        data_type: string
        tests: [not_null]
      - name: job_title
        data_type: string
        tests: [not_null]
      - name: min_wage
        data_type: int64
      - name: max_wage
        data_type: int64
      - name: average_wage
        data_type: float64
      - name: job_count
        data_type: int64
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: datetime

    tests:
      - unique_combination_of_columns:
          combination_of_columns:
            - company_name
            - job_title

