
version: 2

sources:
  - name: cs329e_xh_raw
    database: silken-fortress-448205-p9
    schema: cs329e_xh_raw  
    tables:
      - name: approval_rate_by_month
      - name: city_approval_rate
      - name: company_approval_rate
      - name: company_wage_level
      - name: industry_approval_rate
      - name: major_wage_level
      - name: soc_wage_level
      - name: state_approval_rate
      - name: state_wage_level
      - name: wage_level_by_industry
